name: Sync Docker Image
run-name: ${{ github.actor }} is running GitHub Actions
on: [push]
jobs:
  Sync-Docker-Image-Actions:
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: login to docker registry
        run: |
          docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PWD }}" "${{ secrets.DOCKER_REGISTRY }}"
      - name: execute sync.sh
        run: |
          if [[ "${{ matrix.platform }}" == "linux/arm64" ]]; then
              NS="${{ secrets.DOCKER_NS_ARM }}"
          else
              NS="${{ secrets.DOCKER_NS }}"
          fi
          bash "${{ github.workspace }}/sync.sh" "${{ github.workspace }}/images.txt" "${{ secrets.DOCKER_REGISTRY }}" "$NS" "${{ matrix.platform }}"
      - run: echo "This job's status is ${{ job.status }}"
